name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
          echo "Hello How are you"
          echo "Hello How are you"
      - name: Print goodbye
        run: echo "Goodbye!"
